config/routes.rb
Rails.application.routes.draw do
  root 'locations#index'
  resources :locations
 

end

app/models/location.rb
class Location < ActiveRecord::Base
geocoded_by :full_street_address   
after_validation :geocode          

  def full_street_address
  	"#{address}, #{city}, GA"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  include LocationsHelper


  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @buses = HTTParty.get("http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus")
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @buses = HTTParty.get("http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus")
    @bus_count = 0

    @nearby_buses = []

    @buses.each do |bus|
      if nearby(@location.longitude, @location.latitude, bus['LONGITUDE'].to_f, bus['LATITUDE'].to_f)
        @bus_count += 1
        @nearby_buses.push(bus)
      end
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :address, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
	def nearby(lng1, lat1, lng2, lat2)
		if (lng1-lng2).abs <= 0.01 && (lat1-lat2).abs <= 0.01
			return true 
		else
			return false
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marta</title>
  
    <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyCVC56z0PaBA5M6vQ68FTFqQPDS9oFxNrM"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
<style>
     #map {
      width: 100%;
      height: 400px;
    }
  </style>
</head>
  <body>
    <h3>My Google Maps Demo</h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
            center: { lat: 33.755797, lng: -84.388789},
            zoom: 8
        });
      }
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVC56z0PaBA5M6vQ68FTFqQPDS9oFxNrM&callback=initMap">
    </script>
    <%= yield %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyCVC56z0PaBA5M6vQ68FTFqQPDS9oFxNrM"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>A Bus Nearby?</h1>

<p>input your location</p>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<h2>you are currently at.. </h2>

<p><%= @location.full_street_address %></p>


<h3>The closest buses are ....</h3>

<% if @bus_count == 0 %>
  <p>There are no buses around you. You may consider Lyft or Uber</p>
<% else %>
 <% @nearby_buses.each do |bus| %>
  <strong>Route</strong> <%= bus["ROUTE"] %><br/>
  <strong>Vehicle</strong> <%= bus["VEHICLE"] %><br/>
  <strong>Next Stop</strong> <%= bus["TIMEPOINT"] %><br/>
 <% end %>
<% end %>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<br>
<%= link_to 'Actually, I\'m at...', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

<div id="map-canvas">
  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
</div>